NCEAS/datamgmt

R/package_copy.R
First version, function works for packages with one level of children.  Not ready for code review yet, next version will be.
=> First version of package_copy

R/package_copy.R
Resolve #4.  I'm going to open another issue requesting review for these functions.
=> Resolve #4 

R/add_creator_id.R
=> function to add creator ref id or orcid. first draft

R/data_objects_exist.R
Added a function to check if data objects given a list of metadata identifiers.  This is intended to assist in preparation for the carbon synthesis working group.
=> Add function to check if data objects exist in list of packages

R/package_copy.R
Added EML metadata updates to clone_package function.  Wrote helper function to check metadata quality as well.
=> Added EML update to clone_package

R/get_awards.R
=> added "AON" to fundProgramNames searched

R/eml_data_qa.R
@maier-m can you merge this please?
=> Qa attributes

R/create_dummy_package2.R
from hard link to `file.path(system.file(package = "datamgmt"), "dummy_meta_full.xml")`
=> changed link to dummy_meta_full.xml

tests/testthat/test_add_creator_id.R, tests/testthat/test_create_dummy_package2.R, tests/testthat/test_download_package.R, tests/testthat/test_edit_attribute.R, tests/testthat/test_excel_to_csv.R, tests/testthat/test_get_awards.R, tests/testthat/test_get_eml_attributes.R, tests/testthat/test_return_eml_units.R, tests/testthat/test_which_in_eml.R
removed extra library calls; did basic code cleaning/re-formatting
=> Clean tests

R/query_all_versions.R, man/query_all_versions.Rd, man/query_solr_metadata.Rd, tests/testthat/test_query_all_versions.R
=> Minor changes to query_all_versions

R/eml_data_qa.R
@dmullen17 or @maier-m can one of you guys review this PR? This fixes the bugs listed in #145.
=> Fixes for QA package bugs

R/eml_data_qa.R
Add function to check if creator field is present in EML.
=> Add qa_creator_present function

DESCRIPTION, R/eml_data_qa.R
Add QA functions for checking existence and completeness of creator info
=> Add QA functions for creator info

R/eml_data_qa.R
Add QA functions for existence and completeness of contact info
=> Add QA functions for contact info

R/qa_package.R, man/qa_attributes.Rd, man/qa_package.Rd
Remove `header_row_number` from `qa_package`.
=> Refactor qa_package

.travis.yml, DESCRIPTION, R/clone_package.R, R/qa_package.R, man/copy_package.Rd, man/qa_package.Rd
Updated `clone_package` error messages and documentation.  Close #189
=> updated clone_package error messages and documentation

R/qa_package.R, tests/testthat/test_download_package.R
- fix QA package so it works with references
- fix some tests
=> QA package references fix

R/qa_package.R
=> have QA package give better error information, and fix a bug

R/clone_package.R
Fixes a bug that Rani ran into
=> set access on resource map if a new one is created

.gitignore, .travis.yml, DESCRIPTION, R/categorize_dataset.R, index.Rmd, man/categorize_dataset.Rd, tests/testthat/test_categorize_dataset.R
- overwrites themes if set to TRUE
- checks for other versions in the sheet
- added better testing
=> Support for dois already in sheet and overwriting themes

R/categorize_dataset.R, tests/testthat/test_categorize_dataset.R
=> change successful categorization to message

R/categorize_dataset.R
Addresses this issue:
>Thanks to Julia, we noticed that the datasets that does not contain any keywords might not be in the dataset_categorization spreadsheet. This was found because this dataset didn't have any keywords.
=> add to dataset_categorization to check for columns returned by solr
